version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: super
       POSTGRES_DB: users_data
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
      - ./pg-data:/var/lib/postgresql/data
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
       MONGO_INITDB_ROOT_USERNAME: mongo
       MONGO_INITDB_ROOT_PASSWORD: super
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: super
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
     - "8081:8081"
    depends_on:
      - mongodb

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  
  python:
    build: .
    container_name: python_app
    ports:
     - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres

 # metabase:
 #   image: metabase/metabase:latest-debian
 #   container_name: metabase
 #   ports:
 #     - "3000:3000"
 #   environment:
 #     - MB_DB_FILE=/metabase-data/metabase.db
 #   volumes:
 #     - ./metabase-data:/metabase-data
 #     - ./plugins:/plugins
 #     - ./:/data



volumes:
  pg_data:
  mongo_data:






